<?php

return [
    'status' => [
        'created' => 'created',
        'approved' => 'approved',
        'canceled' => 'canceled',
        'completed' => 'completed',
        'failed' => 'failed',
        'rejected' => 'rejected',
        'success' => 'success',
    ],
    'message' => [
        'get_detail_success' => 'get_detail_success',
        'get_list_success' => 'get_list_success',
        'not_found' => 'not_found',
        'update_failed' => 'update_failed',
        'update_success' => 'update_success',
        'create_success' => 'create_success',
        'create_failed' => 'create_failed',
        'delete_success' => 'delete_success',
        'delete_failed' => 'delete_failed',
        'permission_denied' => 'permission_denied',
        'already_exist' => 'already_exist',
        'user_identify_exist' => 'user_identify_exist',
        'email_already_exists' => 'email_already_exists',
        'fetch_success' => 'fetch_success',
        'fetch_failure' => 'fetch_failure',
        'update_failure' => 'update_failure',
        'authentication_success' => 'authentication_success',
        'authentication_failure' => 'authentication_failure',
        'logout_success' => 'logout_success',
        'logout_failure' => 'logout_failure',
        'token_refresh_success' => 'token_refresh_success',
        'token_refresh_failure' => 'token_refresh_failure',
        'user_data_retrieved' => 'user_data_retrieved',
        'incorrect_current_password' => 'incorrect_current_password',
        'password_reuse_error' => 'password_reuse_error',
        'password_update_success' => 'password_update_success',
        'password_update_failure' => 'password_update_failure',
        'unauthorized_access' => 'unauthorized_access',
        'credentials_do_not_match_record' => 'credentials_do_not_match_record',
        'already_creator' => 'already_creator',
        'already_request_creator' => 'already_request_creator',
        'email_has_not_been_verified' => 'email_has_not_been_verified',
        'reaction_already_exist' => 'reaction_already_exist',
        'plan_already_exists_in_the_post' => 'plan_already_exists_in_the_post',
        'upload_success' => 'upload_success',
        'webhook_success' => 'webhook_success',
        'webhook_failed' => 'webhook_failed',
        'timestamp_expired' => 'timestamp_expired',
        'invalid_signature' => 'invalid_signature',
        'reaction_failed' => 'reaction_failed',
        'bookmark_failed' => 'bookmark_failed',
        'follow_failed' => 'follow_failed',
        'cannot_follow_yourself' => 'cannot_follow_yourself',
        'webhook_missing_signature_or_timestamp' => 'webhook_missing_signature_or_timestamp',
    ],
    'reaction' => [
        'like' => 'like',
    ],
    'mail' => [
    ],

    'per_page' => 10,
    'otp_request_limit' => 5,
    'default_method_payment' => 'stripe',
    'mockup_failed_subscription' => [1111, 2222, 3333, 4444, 5555],
];
